#!/bin/bash
set -eu -o pipefail

# Use aria2 to bulk fetch all the profile URLs generated by
# generate-profile-urls.sh. Pass the output of that to stdin here.

mkdir -p profiles
aria2 --log aria-log.txt --dir profiles --split 1 --file-allocation none \
    --max-concurrent-downloads 16 --max-connection-per-server 16 \
    --input-file -
